### ISSUE TITLE
I do not understand why the _str argument is specified for BaseConv

### ISSUE THREAD

**Issue by yanickrochon** [caub/base-conv#3]
Why is this argument specified ?

https://github.com/caub/baseconv/blob/247a8835a3d89ce716df719f94bea8139ebe8e2e/index.js#L11

There is no need for it as it is overridden in the returning function.

**Comment by caub** [comment]
correct, we should remove _str from the contructor arguments

**Comment by caub** [comment]
fixed by 66faa09593d66cc706baa47d38d7458f87374a5d
